Added tests for 11.3.6
SymbiFlow/sv-tests pull request #1436
Opened 2021-04-04 18:52 UTC by Prahitha

#612

2021-04-07 07:58 UTC, tgorochowik requested changes
Thank you for contribution! Please see the comments below

2021-04-07 07:58 UTC, tgorochowik commented on tests/chapter-11/11.3.6--assign_in_exp-sim.sv
> +    $display(":assert: (b == (c-1))");
Please try to make the indentations the same

2021-04-07 07:58 UTC, tgorochowik commented on tests/chapter-11/11.3.6--assign_in_exp-sim.sv
> +endmodule
Can you add a newline at the end of all the tests?

2021-04-07 07:59 UTC, tgorochowik commented on tests/chapter-11/11.3.6--assign_in_expression-sim.sv
> +    $display(":assert: (b == (c+1))");
The log of the simulation is evaluated by python (we look for the `:assert:` statements). To make it work we need to substitute `b` and `c` with their values, see this as an example:
https://github.com/SymbiFlow/sv-tests/blob/740d4ae9ba4e8b40bebc47abc2f2f6e4c5abb391/tests/chapter-7/arrays/unpacked/reduction-methods/sum.sv#L16

2021-04-07 08:37 UTC, Prahitha commented on tests/chapter-11/11.3.6--assign_in_expression-sim.sv
> +    $display(":assert: (b == (c+1))");
So here, it would be `$display(":assert: (%d == %d), b, (c+1))`?

2021-04-07 08:47 UTC, Prahitha commented on tests/chapter-11/11.3.6--assign_in_exp-sim.sv
> +    $display(":assert: (b == (c-1))");
I saw a couple of examples and they had the assertion in a separate block, for instance: https://github.com/SymbiFlow/sv-tests/blob/740d4ae9ba4e8b40bebc47abc2f2f6e4c5abb391/tests/chapter-11/11.3.6--assign_in_expr-sim.sv#L14-L17
So I was wondering, is it for syntax or code readability?

2021-04-07 08:48 UTC, tgorochowik commented on tests/chapter-11/11.3.6--assign_in_expression-sim.sv
> +    $display(":assert: (b == (c+1))");
yes, that should work

2021-04-07 15:28 UTC, tgorochowik reviewed
These changes look great, thank you for your contribution!

One final request: can you please squash your commits together? Separating changes into separate commits is a good idea if you're adding two distinct things. Here it adds the tests and then a separate commit fixes them, so it would be best to have this as as single commit to make the history cleaner

2021-04-08 10:07 UTC, Prahitha commented
Hope I did it right, thanks for the help!

2021-04-08 10:46 UTC, tgorochowik approved these changes
LGTM, thanks!

2021-04-08 12:39 UTC, merged